[BLD] Add support for NumPy 2.0 wheels (#629)
* build: Add support for NumPy 2.0 wheels [build wheels]

* Add numpy>=2.0.0 to build-system requires to build NumPy 1.x and 2.x compatible
  wheels.
   - c.f. https://numpy.org/doc/stable/dev/depending_on_numpy.html#numpy-2-0-specific-advice
   - As NumPy 2.0 is Python 3.9+, also need to conditionally support 'oldest-supported-numpy'
     for Python 3.8.
* Remove wheel from build-system requires as it is never required and injected
  automatically by setuptools only when needed.
   - c.f. https://learn.scientific-python.org/development/guides/packaging-classic/

* build: Remove setup_requires metadata

* Remove setup_requires as it is deprecated and should defer to PEP 517/518.
   - c.f. https://learn.scientific-python.org/development/guides/packaging-classic/#pep-517518-support-high-priority

* fix: Use np.inf to avoid AttributeError

* Avoids:

  AttributeError: `np.infty` was removed in the NumPy 2.0 release.
  Use `np.inf` instead.

  AttributeError: `np.Inf` was removed in the NumPy 2.0 release.
  Use `np.inf` instead.

* docs: Add NumPy 2.0 support to release notes