fix: Use np.inf to avoid AttributeError
* Avoids:

  AttributeError: `np.infty` was removed in the NumPy 2.0 release.
  Use `np.inf` instead.

  AttributeError: `np.Inf` was removed in the NumPy 2.0 release.
  Use `np.inf` instead.